name: pipeline

on:
  pull_request:
    branches:
      - 'release-*'
      - 'master'
    tags-ignore:
      - '*'

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: webpage install, build, and test
        uses: actions/setup-node@v2

      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        id: install

      - run: npm i -g lerna
        id: lerna

      - run: lerna bootstrap
        id: bootstrap

      - run: yarn run build
        id: turbo

      - run: lerna exec npm pack
        id: pack

      - run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          files: |
            LICENSE.md
            packages/**/*.tgz
        id: 'automatic_releases'
